apiVersion: v1
kind: Service
metadata:
  name: worker-service
spec:
  type: ClusterIP # only works inside the kubernetes cluster, you cant access via internet, only accessible to communication via ingress or gateway
  selector:
    type: worker
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
