apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: blog-backoffice
spec:
  replicas: 3
  selector:
    matchLabels:
      type: backend
  template:
    metadata:
      labels:
        type: backend
    spec:
      containers:
        - name: backend
          image: davimoreira27/blog-platform:backend-v1.0
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: database

            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username

            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password

            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: port
